# Generated by Django 6.0 on 2026-01-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_status_profile_social_hackerrank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('employed', 'Employed'), ('open', 'Open to Work'), ('hiring', 'Hiring'), ('opportunity', 'Open to Opportunities')], default='employed', max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
