# Generated by Django 6.0 on 2026-01-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_job_status_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProfileView',
        ),
    ]
