# Generated by Django 6.0 on 2026-01-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_views_delete_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
