# Generated by Django 6.0 on 2026-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
